version: "3"

services:

  db:
    image: mariadb:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=testedb
      - MYSQL_ROOT_PASSWORD=teste
    ports: 
      - "3306:3306"
    networks:
      - net

networks:
  net:
    driver: bridge